### ISSUE TITLE
Ubuntu 18.04.5 LTS - Envoy Nightly builds seem to be broken

### ISSUE THREAD

**Issue by techpavan** [tetratelabs/getenvoy-package#121]
**Describe the bug**
The latest Envoy build available from the nightly channel is from April 30. It is much older than the stable channel which is from May 11. I am following the installation procedure documented here: https://www.getenvoy.io/install/envoy/ubuntu/

The binaries are available at bintray and the latest is 2 months old: https://bintray.com/tetrate/getenvoy-deb/getenvoy-envoy#files/pool%2Fnightly%2Fg%2Fgetenvoy-envoy

Please have it addressed as Envoy has few feature changes which are not available in the stable release.

**Expected behavior**
Nightly builds should be more frequent. At least once a day.

**System Information (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS

**Comment by techpavan** [comment]
Sharing my workaround if anyone else happen to go through the same problem. Deploy a docker container and copy the `/usr/local/bin/envoy` binary to local `/usr/bin/envoy` location. This definitely requires having some exposure docker, but saves a lot of time breaking head on building it manually if that territory is unknown.

**Comment by codefromthecrypt** [comment]
the list made here does effectively the same thing http://archive.tetratelabs.io/envoy/envoy-versions.json except using [car](https://github.com/tetratelabs/car) instead of docker as it allows more flexibility like pulling a version out of envoy-windows

https://github.com/tetratelabs/archive-envoy/blob/master/bin/car_envoy.sh

Meanwhile, this repo is being archived you can look at https://www.getenvoy.io for options moving forward
