### ISSUE TITLE
Bintray has been sunset, could not install envoy anymore

### ISSUE THREAD

**Issue by lyrixx** [tetratelabs/getenvoy-package#123]
https://bintray.com => 

> To streamline the productivity of the JFrog Platform we will be sunsetting Bintray, GoCenter, and ChartCenter services on May 1st, 2021

**Comment by codefromthecrypt** [comment]
Thanks for reporting, and sorry that you've hit a problem. The last published packages are in cloud smith, not bintray. Apologize but the docs are not updated yet https://github.com/envoyproxy/envoy/pull/17246

We've updated the website for options moving forward because this project is canceled due to trademark issues with The Linux Foundation https://getenvoy.io
